services:
  
  postgres:
    image: postgres:16-alpine
    container_name: sportslink-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: sportslink_test
      POSTGRES_USER: sportslink
      POSTGRES_PASSWORD: sportslink
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  minio:
    image: minio/minio:RELEASE.2024-01-18T22-51-28Z
    container_name: sportslink-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    restart: unless-stopped

  createbuckets:
    image: minio/mc:RELEASE.2024-01-16T16-06-34Z
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/sportslink-images;
      /usr/bin/mc anonymous set download myminio/sportslink-images;
      exit 0;
      "
  
  app:
    build: .
    container_name: sportslink-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/sportslink_test
      SPRING_DATASOURCE_USERNAME: sportslink
      SPRING_DATASOURCE_PASSWORD: sportslink
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      MINIO_URL: http://minio:9000
      MINIO_PUBLIC_URL: http://192.168.160.31:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET_NAME: sportslink-images
    depends_on:
      - postgres
      - minio
    restart: always

volumes:
  postgres-data:
  minio-data:


networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16